language: nodejs

install:
  - nvm install v8.9.1
  - npm run setup

before_script:
  - npm run postinstall

script:
  - npm run start

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: $HEROKU_APP_NAME
